/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the OBCloudPagingDataOcpDbUserDtoV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBCloudPagingDataOcpDbUserDtoV2{}

// OBCloudPagingDataOcpDbUserDtoV2 struct for OBCloudPagingDataOcpDbUserDtoV2
type OBCloudPagingDataOcpDbUserDtoV2 struct {
	DataList []OcpDbUserDtoV2 `json:"dataList,omitempty"`
	Total *int64 `json:"total,omitempty"`
	HasMore *bool `json:"hasMore,omitempty"`
}

// NewOBCloudPagingDataOcpDbUserDtoV2 instantiates a new OBCloudPagingDataOcpDbUserDtoV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBCloudPagingDataOcpDbUserDtoV2() *OBCloudPagingDataOcpDbUserDtoV2 {
	this := OBCloudPagingDataOcpDbUserDtoV2{}
	return &this
}

// NewOBCloudPagingDataOcpDbUserDtoV2WithDefaults instantiates a new OBCloudPagingDataOcpDbUserDtoV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBCloudPagingDataOcpDbUserDtoV2WithDefaults() *OBCloudPagingDataOcpDbUserDtoV2 {
	this := OBCloudPagingDataOcpDbUserDtoV2{}
	return &this
}

// GetDataList returns the DataList field value if set, zero value otherwise.
func (o *OBCloudPagingDataOcpDbUserDtoV2) GetDataList() []OcpDbUserDtoV2 {
	if o == nil || IsNil(o.DataList) {
		var ret []OcpDbUserDtoV2
		return ret
	}
	return o.DataList
}

// GetDataListOk returns a tuple with the DataList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OBCloudPagingDataOcpDbUserDtoV2) GetDataListOk() ([]OcpDbUserDtoV2, bool) {
	if o == nil || IsNil(o.DataList) {
		return nil, false
	}
	return o.DataList, true
}

// HasDataList returns a boolean if a field has been set.
func (o *OBCloudPagingDataOcpDbUserDtoV2) HasDataList() bool {
	if o != nil && !IsNil(o.DataList) {
		return true
	}

	return false
}

// SetDataList gets a reference to the given []OcpDbUserDtoV2 and assigns it to the DataList field.
func (o *OBCloudPagingDataOcpDbUserDtoV2) SetDataList(v []OcpDbUserDtoV2) {
	o.DataList = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *OBCloudPagingDataOcpDbUserDtoV2) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OBCloudPagingDataOcpDbUserDtoV2) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *OBCloudPagingDataOcpDbUserDtoV2) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *OBCloudPagingDataOcpDbUserDtoV2) SetTotal(v int64) {
	o.Total = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *OBCloudPagingDataOcpDbUserDtoV2) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OBCloudPagingDataOcpDbUserDtoV2) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *OBCloudPagingDataOcpDbUserDtoV2) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *OBCloudPagingDataOcpDbUserDtoV2) SetHasMore(v bool) {
	o.HasMore = &v
}

func (o OBCloudPagingDataOcpDbUserDtoV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBCloudPagingDataOcpDbUserDtoV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataList) {
		toSerialize["dataList"] = o.DataList
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	return toSerialize, nil
}

type NullableOBCloudPagingDataOcpDbUserDtoV2 struct {
	value *OBCloudPagingDataOcpDbUserDtoV2
	isSet bool
}

func (v NullableOBCloudPagingDataOcpDbUserDtoV2) Get() *OBCloudPagingDataOcpDbUserDtoV2 {
	return v.value
}

func (v *NullableOBCloudPagingDataOcpDbUserDtoV2) Set(val *OBCloudPagingDataOcpDbUserDtoV2) {
	v.value = val
	v.isSet = true
}

func (v NullableOBCloudPagingDataOcpDbUserDtoV2) IsSet() bool {
	return v.isSet
}

func (v *NullableOBCloudPagingDataOcpDbUserDtoV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBCloudPagingDataOcpDbUserDtoV2(val *OBCloudPagingDataOcpDbUserDtoV2) *NullableOBCloudPagingDataOcpDbUserDtoV2 {
	return &NullableOBCloudPagingDataOcpDbUserDtoV2{value: val, isSet: true}
}

func (v NullableOBCloudPagingDataOcpDbUserDtoV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBCloudPagingDataOcpDbUserDtoV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


