/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ProxyClusterInfoDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProxyClusterInfoDTO{}

// ProxyClusterInfoDTO struct for ProxyClusterInfoDTO
type ProxyClusterInfoDTO struct {
	ProxyClusterId *string `json:"proxyClusterId,omitempty"`
	ProxyMode *string `json:"proxyMode,omitempty"`
	Zone *string `json:"zone,omitempty"`
	UnitSpec *string `json:"unitSpec,omitempty"`
	UnitNum *int32 `json:"unitNum,omitempty"`
	UnitNumLimit *int32 `json:"unitNumLimit,omitempty"`
	Status *string `json:"status,omitempty"`
	ProxyServiceVersion *string `json:"proxyServiceVersion,omitempty"`
	ProxyVersion *string `json:"proxyVersion,omitempty"`
	CreateTime *string `json:"createTime,omitempty"`
	ExpireTime *string `json:"expireTime,omitempty"`
}

// NewProxyClusterInfoDTO instantiates a new ProxyClusterInfoDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProxyClusterInfoDTO() *ProxyClusterInfoDTO {
	this := ProxyClusterInfoDTO{}
	return &this
}

// NewProxyClusterInfoDTOWithDefaults instantiates a new ProxyClusterInfoDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProxyClusterInfoDTOWithDefaults() *ProxyClusterInfoDTO {
	this := ProxyClusterInfoDTO{}
	return &this
}

// GetProxyClusterId returns the ProxyClusterId field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetProxyClusterId() string {
	if o == nil || IsNil(o.ProxyClusterId) {
		var ret string
		return ret
	}
	return *o.ProxyClusterId
}

// GetProxyClusterIdOk returns a tuple with the ProxyClusterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetProxyClusterIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyClusterId) {
		return nil, false
	}
	return o.ProxyClusterId, true
}

// HasProxyClusterId returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasProxyClusterId() bool {
	if o != nil && !IsNil(o.ProxyClusterId) {
		return true
	}

	return false
}

// SetProxyClusterId gets a reference to the given string and assigns it to the ProxyClusterId field.
func (o *ProxyClusterInfoDTO) SetProxyClusterId(v string) {
	o.ProxyClusterId = &v
}

// GetProxyMode returns the ProxyMode field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetProxyMode() string {
	if o == nil || IsNil(o.ProxyMode) {
		var ret string
		return ret
	}
	return *o.ProxyMode
}

// GetProxyModeOk returns a tuple with the ProxyMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetProxyModeOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyMode) {
		return nil, false
	}
	return o.ProxyMode, true
}

// HasProxyMode returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasProxyMode() bool {
	if o != nil && !IsNil(o.ProxyMode) {
		return true
	}

	return false
}

// SetProxyMode gets a reference to the given string and assigns it to the ProxyMode field.
func (o *ProxyClusterInfoDTO) SetProxyMode(v string) {
	o.ProxyMode = &v
}

// GetZone returns the Zone field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetZone() string {
	if o == nil || IsNil(o.Zone) {
		var ret string
		return ret
	}
	return *o.Zone
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetZoneOk() (*string, bool) {
	if o == nil || IsNil(o.Zone) {
		return nil, false
	}
	return o.Zone, true
}

// HasZone returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasZone() bool {
	if o != nil && !IsNil(o.Zone) {
		return true
	}

	return false
}

// SetZone gets a reference to the given string and assigns it to the Zone field.
func (o *ProxyClusterInfoDTO) SetZone(v string) {
	o.Zone = &v
}

// GetUnitSpec returns the UnitSpec field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetUnitSpec() string {
	if o == nil || IsNil(o.UnitSpec) {
		var ret string
		return ret
	}
	return *o.UnitSpec
}

// GetUnitSpecOk returns a tuple with the UnitSpec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetUnitSpecOk() (*string, bool) {
	if o == nil || IsNil(o.UnitSpec) {
		return nil, false
	}
	return o.UnitSpec, true
}

// HasUnitSpec returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasUnitSpec() bool {
	if o != nil && !IsNil(o.UnitSpec) {
		return true
	}

	return false
}

// SetUnitSpec gets a reference to the given string and assigns it to the UnitSpec field.
func (o *ProxyClusterInfoDTO) SetUnitSpec(v string) {
	o.UnitSpec = &v
}

// GetUnitNum returns the UnitNum field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetUnitNum() int32 {
	if o == nil || IsNil(o.UnitNum) {
		var ret int32
		return ret
	}
	return *o.UnitNum
}

// GetUnitNumOk returns a tuple with the UnitNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetUnitNumOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitNum) {
		return nil, false
	}
	return o.UnitNum, true
}

// HasUnitNum returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasUnitNum() bool {
	if o != nil && !IsNil(o.UnitNum) {
		return true
	}

	return false
}

// SetUnitNum gets a reference to the given int32 and assigns it to the UnitNum field.
func (o *ProxyClusterInfoDTO) SetUnitNum(v int32) {
	o.UnitNum = &v
}

// GetUnitNumLimit returns the UnitNumLimit field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetUnitNumLimit() int32 {
	if o == nil || IsNil(o.UnitNumLimit) {
		var ret int32
		return ret
	}
	return *o.UnitNumLimit
}

// GetUnitNumLimitOk returns a tuple with the UnitNumLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetUnitNumLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitNumLimit) {
		return nil, false
	}
	return o.UnitNumLimit, true
}

// HasUnitNumLimit returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasUnitNumLimit() bool {
	if o != nil && !IsNil(o.UnitNumLimit) {
		return true
	}

	return false
}

// SetUnitNumLimit gets a reference to the given int32 and assigns it to the UnitNumLimit field.
func (o *ProxyClusterInfoDTO) SetUnitNumLimit(v int32) {
	o.UnitNumLimit = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ProxyClusterInfoDTO) SetStatus(v string) {
	o.Status = &v
}

// GetProxyServiceVersion returns the ProxyServiceVersion field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetProxyServiceVersion() string {
	if o == nil || IsNil(o.ProxyServiceVersion) {
		var ret string
		return ret
	}
	return *o.ProxyServiceVersion
}

// GetProxyServiceVersionOk returns a tuple with the ProxyServiceVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetProxyServiceVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyServiceVersion) {
		return nil, false
	}
	return o.ProxyServiceVersion, true
}

// HasProxyServiceVersion returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasProxyServiceVersion() bool {
	if o != nil && !IsNil(o.ProxyServiceVersion) {
		return true
	}

	return false
}

// SetProxyServiceVersion gets a reference to the given string and assigns it to the ProxyServiceVersion field.
func (o *ProxyClusterInfoDTO) SetProxyServiceVersion(v string) {
	o.ProxyServiceVersion = &v
}

// GetProxyVersion returns the ProxyVersion field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetProxyVersion() string {
	if o == nil || IsNil(o.ProxyVersion) {
		var ret string
		return ret
	}
	return *o.ProxyVersion
}

// GetProxyVersionOk returns a tuple with the ProxyVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetProxyVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyVersion) {
		return nil, false
	}
	return o.ProxyVersion, true
}

// HasProxyVersion returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasProxyVersion() bool {
	if o != nil && !IsNil(o.ProxyVersion) {
		return true
	}

	return false
}

// SetProxyVersion gets a reference to the given string and assigns it to the ProxyVersion field.
func (o *ProxyClusterInfoDTO) SetProxyVersion(v string) {
	o.ProxyVersion = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetCreateTime() string {
	if o == nil || IsNil(o.CreateTime) {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetCreateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *ProxyClusterInfoDTO) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetExpireTime returns the ExpireTime field value if set, zero value otherwise.
func (o *ProxyClusterInfoDTO) GetExpireTime() string {
	if o == nil || IsNil(o.ExpireTime) {
		var ret string
		return ret
	}
	return *o.ExpireTime
}

// GetExpireTimeOk returns a tuple with the ExpireTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProxyClusterInfoDTO) GetExpireTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ExpireTime) {
		return nil, false
	}
	return o.ExpireTime, true
}

// HasExpireTime returns a boolean if a field has been set.
func (o *ProxyClusterInfoDTO) HasExpireTime() bool {
	if o != nil && !IsNil(o.ExpireTime) {
		return true
	}

	return false
}

// SetExpireTime gets a reference to the given string and assigns it to the ExpireTime field.
func (o *ProxyClusterInfoDTO) SetExpireTime(v string) {
	o.ExpireTime = &v
}

func (o ProxyClusterInfoDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProxyClusterInfoDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProxyClusterId) {
		toSerialize["proxyClusterId"] = o.ProxyClusterId
	}
	if !IsNil(o.ProxyMode) {
		toSerialize["proxyMode"] = o.ProxyMode
	}
	if !IsNil(o.Zone) {
		toSerialize["zone"] = o.Zone
	}
	if !IsNil(o.UnitSpec) {
		toSerialize["unitSpec"] = o.UnitSpec
	}
	if !IsNil(o.UnitNum) {
		toSerialize["unitNum"] = o.UnitNum
	}
	if !IsNil(o.UnitNumLimit) {
		toSerialize["unitNumLimit"] = o.UnitNumLimit
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ProxyServiceVersion) {
		toSerialize["proxyServiceVersion"] = o.ProxyServiceVersion
	}
	if !IsNil(o.ProxyVersion) {
		toSerialize["proxyVersion"] = o.ProxyVersion
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.ExpireTime) {
		toSerialize["expireTime"] = o.ExpireTime
	}
	return toSerialize, nil
}

type NullableProxyClusterInfoDTO struct {
	value *ProxyClusterInfoDTO
	isSet bool
}

func (v NullableProxyClusterInfoDTO) Get() *ProxyClusterInfoDTO {
	return v.value
}

func (v *NullableProxyClusterInfoDTO) Set(val *ProxyClusterInfoDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableProxyClusterInfoDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableProxyClusterInfoDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProxyClusterInfoDTO(val *ProxyClusterInfoDTO) *NullableProxyClusterInfoDTO {
	return &NullableProxyClusterInfoDTO{value: val, isSet: true}
}

func (v NullableProxyClusterInfoDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProxyClusterInfoDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


