/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the CreateMcTenantAddressRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMcTenantAddressRequest{}

// CreateMcTenantAddressRequest struct for CreateMcTenantAddressRequest
type CreateMcTenantAddressRequest struct {
	VipServiceType *string `json:"vipServiceType,omitempty"`
	VpcConnectionInfoId *string `json:"vpcConnectionInfoId,omitempty"`
}

// NewCreateMcTenantAddressRequest instantiates a new CreateMcTenantAddressRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMcTenantAddressRequest() *CreateMcTenantAddressRequest {
	this := CreateMcTenantAddressRequest{}
	return &this
}

// NewCreateMcTenantAddressRequestWithDefaults instantiates a new CreateMcTenantAddressRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMcTenantAddressRequestWithDefaults() *CreateMcTenantAddressRequest {
	this := CreateMcTenantAddressRequest{}
	return &this
}

// GetVipServiceType returns the VipServiceType field value if set, zero value otherwise.
func (o *CreateMcTenantAddressRequest) GetVipServiceType() string {
	if o == nil || IsNil(o.VipServiceType) {
		var ret string
		return ret
	}
	return *o.VipServiceType
}

// GetVipServiceTypeOk returns a tuple with the VipServiceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcTenantAddressRequest) GetVipServiceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.VipServiceType) {
		return nil, false
	}
	return o.VipServiceType, true
}

// HasVipServiceType returns a boolean if a field has been set.
func (o *CreateMcTenantAddressRequest) HasVipServiceType() bool {
	if o != nil && !IsNil(o.VipServiceType) {
		return true
	}

	return false
}

// SetVipServiceType gets a reference to the given string and assigns it to the VipServiceType field.
func (o *CreateMcTenantAddressRequest) SetVipServiceType(v string) {
	o.VipServiceType = &v
}

// GetVpcConnectionInfoId returns the VpcConnectionInfoId field value if set, zero value otherwise.
func (o *CreateMcTenantAddressRequest) GetVpcConnectionInfoId() string {
	if o == nil || IsNil(o.VpcConnectionInfoId) {
		var ret string
		return ret
	}
	return *o.VpcConnectionInfoId
}

// GetVpcConnectionInfoIdOk returns a tuple with the VpcConnectionInfoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMcTenantAddressRequest) GetVpcConnectionInfoIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpcConnectionInfoId) {
		return nil, false
	}
	return o.VpcConnectionInfoId, true
}

// HasVpcConnectionInfoId returns a boolean if a field has been set.
func (o *CreateMcTenantAddressRequest) HasVpcConnectionInfoId() bool {
	if o != nil && !IsNil(o.VpcConnectionInfoId) {
		return true
	}

	return false
}

// SetVpcConnectionInfoId gets a reference to the given string and assigns it to the VpcConnectionInfoId field.
func (o *CreateMcTenantAddressRequest) SetVpcConnectionInfoId(v string) {
	o.VpcConnectionInfoId = &v
}

func (o CreateMcTenantAddressRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMcTenantAddressRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VipServiceType) {
		toSerialize["vipServiceType"] = o.VipServiceType
	}
	if !IsNil(o.VpcConnectionInfoId) {
		toSerialize["vpcConnectionInfoId"] = o.VpcConnectionInfoId
	}
	return toSerialize, nil
}

type NullableCreateMcTenantAddressRequest struct {
	value *CreateMcTenantAddressRequest
	isSet bool
}

func (v NullableCreateMcTenantAddressRequest) Get() *CreateMcTenantAddressRequest {
	return v.value
}

func (v *NullableCreateMcTenantAddressRequest) Set(val *CreateMcTenantAddressRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMcTenantAddressRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMcTenantAddressRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMcTenantAddressRequest(val *CreateMcTenantAddressRequest) *NullableCreateMcTenantAddressRequest {
	return &NullableCreateMcTenantAddressRequest{value: val, isSet: true}
}

func (v NullableCreateMcTenantAddressRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMcTenantAddressRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


