/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ConfirmTenantPlServiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfirmTenantPlServiceRequest{}

// ConfirmTenantPlServiceRequest struct for ConfirmTenantPlServiceRequest
type ConfirmTenantPlServiceRequest struct {
	AddressId *string `json:"addressId,omitempty"`
	EndpointId *string `json:"endpointId,omitempty"`
}

// NewConfirmTenantPlServiceRequest instantiates a new ConfirmTenantPlServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirmTenantPlServiceRequest() *ConfirmTenantPlServiceRequest {
	this := ConfirmTenantPlServiceRequest{}
	return &this
}

// NewConfirmTenantPlServiceRequestWithDefaults instantiates a new ConfirmTenantPlServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmTenantPlServiceRequestWithDefaults() *ConfirmTenantPlServiceRequest {
	this := ConfirmTenantPlServiceRequest{}
	return &this
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *ConfirmTenantPlServiceRequest) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfirmTenantPlServiceRequest) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *ConfirmTenantPlServiceRequest) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *ConfirmTenantPlServiceRequest) SetAddressId(v string) {
	o.AddressId = &v
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *ConfirmTenantPlServiceRequest) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfirmTenantPlServiceRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *ConfirmTenantPlServiceRequest) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *ConfirmTenantPlServiceRequest) SetEndpointId(v string) {
	o.EndpointId = &v
}

func (o ConfirmTenantPlServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfirmTenantPlServiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressId) {
		toSerialize["addressId"] = o.AddressId
	}
	if !IsNil(o.EndpointId) {
		toSerialize["endpointId"] = o.EndpointId
	}
	return toSerialize, nil
}

type NullableConfirmTenantPlServiceRequest struct {
	value *ConfirmTenantPlServiceRequest
	isSet bool
}

func (v NullableConfirmTenantPlServiceRequest) Get() *ConfirmTenantPlServiceRequest {
	return v.value
}

func (v *NullableConfirmTenantPlServiceRequest) Set(val *ConfirmTenantPlServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirmTenantPlServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirmTenantPlServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirmTenantPlServiceRequest(val *ConfirmTenantPlServiceRequest) *NullableConfirmTenantPlServiceRequest {
	return &NullableConfirmTenantPlServiceRequest{value: val, isSet: true}
}

func (v NullableConfirmTenantPlServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirmTenantPlServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


