/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ModifyDatabaseDescriptionRequestV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyDatabaseDescriptionRequestV2{}

// ModifyDatabaseDescriptionRequestV2 struct for ModifyDatabaseDescriptionRequestV2
type ModifyDatabaseDescriptionRequestV2 struct {
	RequestId *string `json:"requestId,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewModifyDatabaseDescriptionRequestV2 instantiates a new ModifyDatabaseDescriptionRequestV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyDatabaseDescriptionRequestV2() *ModifyDatabaseDescriptionRequestV2 {
	this := ModifyDatabaseDescriptionRequestV2{}
	return &this
}

// NewModifyDatabaseDescriptionRequestV2WithDefaults instantiates a new ModifyDatabaseDescriptionRequestV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyDatabaseDescriptionRequestV2WithDefaults() *ModifyDatabaseDescriptionRequestV2 {
	this := ModifyDatabaseDescriptionRequestV2{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ModifyDatabaseDescriptionRequestV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyDatabaseDescriptionRequestV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ModifyDatabaseDescriptionRequestV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ModifyDatabaseDescriptionRequestV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModifyDatabaseDescriptionRequestV2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyDatabaseDescriptionRequestV2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModifyDatabaseDescriptionRequestV2) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModifyDatabaseDescriptionRequestV2) SetDescription(v string) {
	o.Description = &v
}

func (o ModifyDatabaseDescriptionRequestV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyDatabaseDescriptionRequestV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableModifyDatabaseDescriptionRequestV2 struct {
	value *ModifyDatabaseDescriptionRequestV2
	isSet bool
}

func (v NullableModifyDatabaseDescriptionRequestV2) Get() *ModifyDatabaseDescriptionRequestV2 {
	return v.value
}

func (v *NullableModifyDatabaseDescriptionRequestV2) Set(val *ModifyDatabaseDescriptionRequestV2) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyDatabaseDescriptionRequestV2) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyDatabaseDescriptionRequestV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyDatabaseDescriptionRequestV2(val *ModifyDatabaseDescriptionRequestV2) *NullableModifyDatabaseDescriptionRequestV2 {
	return &NullableModifyDatabaseDescriptionRequestV2{value: val, isSet: true}
}

func (v NullableModifyDatabaseDescriptionRequestV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyDatabaseDescriptionRequestV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


