/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the CreateTenantPlServiceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTenantPlServiceResponse{}

// CreateTenantPlServiceResponse struct for CreateTenantPlServiceResponse
type CreateTenantPlServiceResponse struct {
	AddressId *string `json:"addressId,omitempty"`
}

// NewCreateTenantPlServiceResponse instantiates a new CreateTenantPlServiceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTenantPlServiceResponse() *CreateTenantPlServiceResponse {
	this := CreateTenantPlServiceResponse{}
	return &this
}

// NewCreateTenantPlServiceResponseWithDefaults instantiates a new CreateTenantPlServiceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTenantPlServiceResponseWithDefaults() *CreateTenantPlServiceResponse {
	this := CreateTenantPlServiceResponse{}
	return &this
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *CreateTenantPlServiceResponse) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantPlServiceResponse) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *CreateTenantPlServiceResponse) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *CreateTenantPlServiceResponse) SetAddressId(v string) {
	o.AddressId = &v
}

func (o CreateTenantPlServiceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTenantPlServiceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressId) {
		toSerialize["addressId"] = o.AddressId
	}
	return toSerialize, nil
}

type NullableCreateTenantPlServiceResponse struct {
	value *CreateTenantPlServiceResponse
	isSet bool
}

func (v NullableCreateTenantPlServiceResponse) Get() *CreateTenantPlServiceResponse {
	return v.value
}

func (v *NullableCreateTenantPlServiceResponse) Set(val *CreateTenantPlServiceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTenantPlServiceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTenantPlServiceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTenantPlServiceResponse(val *CreateTenantPlServiceResponse) *NullableCreateTenantPlServiceResponse {
	return &NullableCreateTenantPlServiceResponse{value: val, isSet: true}
}

func (v NullableCreateTenantPlServiceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTenantPlServiceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


