/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI{}

// OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI struct for OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI
type OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI struct {
	DataList []DescribeInstancesResponseV2OpenAPI `json:"dataList,omitempty"`
	Total *int64 `json:"total,omitempty"`
	HasMore *bool `json:"hasMore,omitempty"`
}

// NewOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI instantiates a new OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI() *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI {
	this := OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI{}
	return &this
}

// NewOBCloudPagingDataListDescribeInstancesResponseV2OpenAPIWithDefaults instantiates a new OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOBCloudPagingDataListDescribeInstancesResponseV2OpenAPIWithDefaults() *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI {
	this := OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI{}
	return &this
}

// GetDataList returns the DataList field value if set, zero value otherwise.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) GetDataList() []DescribeInstancesResponseV2OpenAPI {
	if o == nil || IsNil(o.DataList) {
		var ret []DescribeInstancesResponseV2OpenAPI
		return ret
	}
	return o.DataList
}

// GetDataListOk returns a tuple with the DataList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) GetDataListOk() ([]DescribeInstancesResponseV2OpenAPI, bool) {
	if o == nil || IsNil(o.DataList) {
		return nil, false
	}
	return o.DataList, true
}

// HasDataList returns a boolean if a field has been set.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) HasDataList() bool {
	if o != nil && !IsNil(o.DataList) {
		return true
	}

	return false
}

// SetDataList gets a reference to the given []DescribeInstancesResponseV2OpenAPI and assigns it to the DataList field.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) SetDataList(v []DescribeInstancesResponseV2OpenAPI) {
	o.DataList = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) SetTotal(v int64) {
	o.Total = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) SetHasMore(v bool) {
	o.HasMore = &v
}

func (o OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataList) {
		toSerialize["dataList"] = o.DataList
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	return toSerialize, nil
}

type NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI struct {
	value *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI
	isSet bool
}

func (v NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) Get() *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI {
	return v.value
}

func (v *NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) Set(val *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) {
	v.value = val
	v.isSet = true
}

func (v NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) IsSet() bool {
	return v.isSet
}

func (v *NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI(val *OBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) *NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI {
	return &NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI{value: val, isSet: true}
}

func (v NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOBCloudPagingDataListDescribeInstancesResponseV2OpenAPI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


