/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the TenantCpuDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantCpuDTO{}

// TenantCpuDTO struct for TenantCpuDTO
type TenantCpuDTO struct {
	TotalCpu *float64 `json:"totalCpu,omitempty"`
	UsedCpu *float64 `json:"usedCpu,omitempty"`
	UnitCpu *float64 `json:"unitCpu,omitempty"`
}

// NewTenantCpuDTO instantiates a new TenantCpuDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantCpuDTO() *TenantCpuDTO {
	this := TenantCpuDTO{}
	return &this
}

// NewTenantCpuDTOWithDefaults instantiates a new TenantCpuDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantCpuDTOWithDefaults() *TenantCpuDTO {
	this := TenantCpuDTO{}
	return &this
}

// GetTotalCpu returns the TotalCpu field value if set, zero value otherwise.
func (o *TenantCpuDTO) GetTotalCpu() float64 {
	if o == nil || IsNil(o.TotalCpu) {
		var ret float64
		return ret
	}
	return *o.TotalCpu
}

// GetTotalCpuOk returns a tuple with the TotalCpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCpuDTO) GetTotalCpuOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalCpu) {
		return nil, false
	}
	return o.TotalCpu, true
}

// HasTotalCpu returns a boolean if a field has been set.
func (o *TenantCpuDTO) HasTotalCpu() bool {
	if o != nil && !IsNil(o.TotalCpu) {
		return true
	}

	return false
}

// SetTotalCpu gets a reference to the given float64 and assigns it to the TotalCpu field.
func (o *TenantCpuDTO) SetTotalCpu(v float64) {
	o.TotalCpu = &v
}

// GetUsedCpu returns the UsedCpu field value if set, zero value otherwise.
func (o *TenantCpuDTO) GetUsedCpu() float64 {
	if o == nil || IsNil(o.UsedCpu) {
		var ret float64
		return ret
	}
	return *o.UsedCpu
}

// GetUsedCpuOk returns a tuple with the UsedCpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCpuDTO) GetUsedCpuOk() (*float64, bool) {
	if o == nil || IsNil(o.UsedCpu) {
		return nil, false
	}
	return o.UsedCpu, true
}

// HasUsedCpu returns a boolean if a field has been set.
func (o *TenantCpuDTO) HasUsedCpu() bool {
	if o != nil && !IsNil(o.UsedCpu) {
		return true
	}

	return false
}

// SetUsedCpu gets a reference to the given float64 and assigns it to the UsedCpu field.
func (o *TenantCpuDTO) SetUsedCpu(v float64) {
	o.UsedCpu = &v
}

// GetUnitCpu returns the UnitCpu field value if set, zero value otherwise.
func (o *TenantCpuDTO) GetUnitCpu() float64 {
	if o == nil || IsNil(o.UnitCpu) {
		var ret float64
		return ret
	}
	return *o.UnitCpu
}

// GetUnitCpuOk returns a tuple with the UnitCpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantCpuDTO) GetUnitCpuOk() (*float64, bool) {
	if o == nil || IsNil(o.UnitCpu) {
		return nil, false
	}
	return o.UnitCpu, true
}

// HasUnitCpu returns a boolean if a field has been set.
func (o *TenantCpuDTO) HasUnitCpu() bool {
	if o != nil && !IsNil(o.UnitCpu) {
		return true
	}

	return false
}

// SetUnitCpu gets a reference to the given float64 and assigns it to the UnitCpu field.
func (o *TenantCpuDTO) SetUnitCpu(v float64) {
	o.UnitCpu = &v
}

func (o TenantCpuDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantCpuDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCpu) {
		toSerialize["totalCpu"] = o.TotalCpu
	}
	if !IsNil(o.UsedCpu) {
		toSerialize["usedCpu"] = o.UsedCpu
	}
	if !IsNil(o.UnitCpu) {
		toSerialize["unitCpu"] = o.UnitCpu
	}
	return toSerialize, nil
}

type NullableTenantCpuDTO struct {
	value *TenantCpuDTO
	isSet bool
}

func (v NullableTenantCpuDTO) Get() *TenantCpuDTO {
	return v.value
}

func (v *NullableTenantCpuDTO) Set(val *TenantCpuDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantCpuDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantCpuDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantCpuDTO(val *TenantCpuDTO) *NullableTenantCpuDTO {
	return &NullableTenantCpuDTO{value: val, isSet: true}
}

func (v NullableTenantCpuDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantCpuDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


