/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ConnectTenantPlServiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectTenantPlServiceRequest{}

// ConnectTenantPlServiceRequest struct for ConnectTenantPlServiceRequest
type ConnectTenantPlServiceRequest struct {
	EndpointId *string `json:"endpointId,omitempty"`
	AddressId *string `json:"addressId,omitempty"`
	UserEndpointAddress *string `json:"userEndpointAddress,omitempty"`
}

// NewConnectTenantPlServiceRequest instantiates a new ConnectTenantPlServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectTenantPlServiceRequest() *ConnectTenantPlServiceRequest {
	this := ConnectTenantPlServiceRequest{}
	return &this
}

// NewConnectTenantPlServiceRequestWithDefaults instantiates a new ConnectTenantPlServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectTenantPlServiceRequestWithDefaults() *ConnectTenantPlServiceRequest {
	this := ConnectTenantPlServiceRequest{}
	return &this
}

// GetEndpointId returns the EndpointId field value if set, zero value otherwise.
func (o *ConnectTenantPlServiceRequest) GetEndpointId() string {
	if o == nil || IsNil(o.EndpointId) {
		var ret string
		return ret
	}
	return *o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectTenantPlServiceRequest) GetEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointId) {
		return nil, false
	}
	return o.EndpointId, true
}

// HasEndpointId returns a boolean if a field has been set.
func (o *ConnectTenantPlServiceRequest) HasEndpointId() bool {
	if o != nil && !IsNil(o.EndpointId) {
		return true
	}

	return false
}

// SetEndpointId gets a reference to the given string and assigns it to the EndpointId field.
func (o *ConnectTenantPlServiceRequest) SetEndpointId(v string) {
	o.EndpointId = &v
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *ConnectTenantPlServiceRequest) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectTenantPlServiceRequest) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *ConnectTenantPlServiceRequest) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *ConnectTenantPlServiceRequest) SetAddressId(v string) {
	o.AddressId = &v
}

// GetUserEndpointAddress returns the UserEndpointAddress field value if set, zero value otherwise.
func (o *ConnectTenantPlServiceRequest) GetUserEndpointAddress() string {
	if o == nil || IsNil(o.UserEndpointAddress) {
		var ret string
		return ret
	}
	return *o.UserEndpointAddress
}

// GetUserEndpointAddressOk returns a tuple with the UserEndpointAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectTenantPlServiceRequest) GetUserEndpointAddressOk() (*string, bool) {
	if o == nil || IsNil(o.UserEndpointAddress) {
		return nil, false
	}
	return o.UserEndpointAddress, true
}

// HasUserEndpointAddress returns a boolean if a field has been set.
func (o *ConnectTenantPlServiceRequest) HasUserEndpointAddress() bool {
	if o != nil && !IsNil(o.UserEndpointAddress) {
		return true
	}

	return false
}

// SetUserEndpointAddress gets a reference to the given string and assigns it to the UserEndpointAddress field.
func (o *ConnectTenantPlServiceRequest) SetUserEndpointAddress(v string) {
	o.UserEndpointAddress = &v
}

func (o ConnectTenantPlServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectTenantPlServiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointId) {
		toSerialize["endpointId"] = o.EndpointId
	}
	if !IsNil(o.AddressId) {
		toSerialize["addressId"] = o.AddressId
	}
	if !IsNil(o.UserEndpointAddress) {
		toSerialize["userEndpointAddress"] = o.UserEndpointAddress
	}
	return toSerialize, nil
}

type NullableConnectTenantPlServiceRequest struct {
	value *ConnectTenantPlServiceRequest
	isSet bool
}

func (v NullableConnectTenantPlServiceRequest) Get() *ConnectTenantPlServiceRequest {
	return v.value
}

func (v *NullableConnectTenantPlServiceRequest) Set(val *ConnectTenantPlServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectTenantPlServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectTenantPlServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectTenantPlServiceRequest(val *ConnectTenantPlServiceRequest) *NullableConnectTenantPlServiceRequest {
	return &NullableConnectTenantPlServiceRequest{value: val, isSet: true}
}

func (v NullableConnectTenantPlServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectTenantPlServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


