/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the McDeleteTenantSecurityIpGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McDeleteTenantSecurityIpGroupResponse{}

// McDeleteTenantSecurityIpGroupResponse struct for McDeleteTenantSecurityIpGroupResponse
type McDeleteTenantSecurityIpGroupResponse struct {
	InstanceId *string `json:"instanceId,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
	SecurityIpGroupName *string `json:"securityIpGroupName,omitempty"`
}

// NewMcDeleteTenantSecurityIpGroupResponse instantiates a new McDeleteTenantSecurityIpGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcDeleteTenantSecurityIpGroupResponse() *McDeleteTenantSecurityIpGroupResponse {
	this := McDeleteTenantSecurityIpGroupResponse{}
	return &this
}

// NewMcDeleteTenantSecurityIpGroupResponseWithDefaults instantiates a new McDeleteTenantSecurityIpGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcDeleteTenantSecurityIpGroupResponseWithDefaults() *McDeleteTenantSecurityIpGroupResponse {
	this := McDeleteTenantSecurityIpGroupResponse{}
	return &this
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *McDeleteTenantSecurityIpGroupResponse) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McDeleteTenantSecurityIpGroupResponse) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *McDeleteTenantSecurityIpGroupResponse) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *McDeleteTenantSecurityIpGroupResponse) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *McDeleteTenantSecurityIpGroupResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McDeleteTenantSecurityIpGroupResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *McDeleteTenantSecurityIpGroupResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *McDeleteTenantSecurityIpGroupResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSecurityIpGroupName returns the SecurityIpGroupName field value if set, zero value otherwise.
func (o *McDeleteTenantSecurityIpGroupResponse) GetSecurityIpGroupName() string {
	if o == nil || IsNil(o.SecurityIpGroupName) {
		var ret string
		return ret
	}
	return *o.SecurityIpGroupName
}

// GetSecurityIpGroupNameOk returns a tuple with the SecurityIpGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McDeleteTenantSecurityIpGroupResponse) GetSecurityIpGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityIpGroupName) {
		return nil, false
	}
	return o.SecurityIpGroupName, true
}

// HasSecurityIpGroupName returns a boolean if a field has been set.
func (o *McDeleteTenantSecurityIpGroupResponse) HasSecurityIpGroupName() bool {
	if o != nil && !IsNil(o.SecurityIpGroupName) {
		return true
	}

	return false
}

// SetSecurityIpGroupName gets a reference to the given string and assigns it to the SecurityIpGroupName field.
func (o *McDeleteTenantSecurityIpGroupResponse) SetSecurityIpGroupName(v string) {
	o.SecurityIpGroupName = &v
}

func (o McDeleteTenantSecurityIpGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McDeleteTenantSecurityIpGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.SecurityIpGroupName) {
		toSerialize["securityIpGroupName"] = o.SecurityIpGroupName
	}
	return toSerialize, nil
}

type NullableMcDeleteTenantSecurityIpGroupResponse struct {
	value *McDeleteTenantSecurityIpGroupResponse
	isSet bool
}

func (v NullableMcDeleteTenantSecurityIpGroupResponse) Get() *McDeleteTenantSecurityIpGroupResponse {
	return v.value
}

func (v *NullableMcDeleteTenantSecurityIpGroupResponse) Set(val *McDeleteTenantSecurityIpGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMcDeleteTenantSecurityIpGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMcDeleteTenantSecurityIpGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcDeleteTenantSecurityIpGroupResponse(val *McDeleteTenantSecurityIpGroupResponse) *NullableMcDeleteTenantSecurityIpGroupResponse {
	return &NullableMcDeleteTenantSecurityIpGroupResponse{value: val, isSet: true}
}

func (v NullableMcDeleteTenantSecurityIpGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcDeleteTenantSecurityIpGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


