/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ModifyTenantPrimaryZoneRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyTenantPrimaryZoneRequest{}

// ModifyTenantPrimaryZoneRequest struct for ModifyTenantPrimaryZoneRequest
type ModifyTenantPrimaryZoneRequest struct {
	PrimaryZone *string `json:"primaryZone,omitempty"`
}

// NewModifyTenantPrimaryZoneRequest instantiates a new ModifyTenantPrimaryZoneRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyTenantPrimaryZoneRequest() *ModifyTenantPrimaryZoneRequest {
	this := ModifyTenantPrimaryZoneRequest{}
	return &this
}

// NewModifyTenantPrimaryZoneRequestWithDefaults instantiates a new ModifyTenantPrimaryZoneRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyTenantPrimaryZoneRequestWithDefaults() *ModifyTenantPrimaryZoneRequest {
	this := ModifyTenantPrimaryZoneRequest{}
	return &this
}

// GetPrimaryZone returns the PrimaryZone field value if set, zero value otherwise.
func (o *ModifyTenantPrimaryZoneRequest) GetPrimaryZone() string {
	if o == nil || IsNil(o.PrimaryZone) {
		var ret string
		return ret
	}
	return *o.PrimaryZone
}

// GetPrimaryZoneOk returns a tuple with the PrimaryZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyTenantPrimaryZoneRequest) GetPrimaryZoneOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryZone) {
		return nil, false
	}
	return o.PrimaryZone, true
}

// HasPrimaryZone returns a boolean if a field has been set.
func (o *ModifyTenantPrimaryZoneRequest) HasPrimaryZone() bool {
	if o != nil && !IsNil(o.PrimaryZone) {
		return true
	}

	return false
}

// SetPrimaryZone gets a reference to the given string and assigns it to the PrimaryZone field.
func (o *ModifyTenantPrimaryZoneRequest) SetPrimaryZone(v string) {
	o.PrimaryZone = &v
}

func (o ModifyTenantPrimaryZoneRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyTenantPrimaryZoneRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrimaryZone) {
		toSerialize["primaryZone"] = o.PrimaryZone
	}
	return toSerialize, nil
}

type NullableModifyTenantPrimaryZoneRequest struct {
	value *ModifyTenantPrimaryZoneRequest
	isSet bool
}

func (v NullableModifyTenantPrimaryZoneRequest) Get() *ModifyTenantPrimaryZoneRequest {
	return v.value
}

func (v *NullableModifyTenantPrimaryZoneRequest) Set(val *ModifyTenantPrimaryZoneRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyTenantPrimaryZoneRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyTenantPrimaryZoneRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyTenantPrimaryZoneRequest(val *ModifyTenantPrimaryZoneRequest) *NullableModifyTenantPrimaryZoneRequest {
	return &NullableModifyTenantPrimaryZoneRequest{value: val, isSet: true}
}

func (v NullableModifyTenantPrimaryZoneRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyTenantPrimaryZoneRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


