/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ModifyInstanceNameRequestV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyInstanceNameRequestV2{}

// ModifyInstanceNameRequestV2 struct for ModifyInstanceNameRequestV2
type ModifyInstanceNameRequestV2 struct {
	RequestId *string `json:"requestId,omitempty"`
	InstanceName *string `json:"instanceName,omitempty"`
}

// NewModifyInstanceNameRequestV2 instantiates a new ModifyInstanceNameRequestV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyInstanceNameRequestV2() *ModifyInstanceNameRequestV2 {
	this := ModifyInstanceNameRequestV2{}
	return &this
}

// NewModifyInstanceNameRequestV2WithDefaults instantiates a new ModifyInstanceNameRequestV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyInstanceNameRequestV2WithDefaults() *ModifyInstanceNameRequestV2 {
	this := ModifyInstanceNameRequestV2{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ModifyInstanceNameRequestV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyInstanceNameRequestV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ModifyInstanceNameRequestV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ModifyInstanceNameRequestV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetInstanceName returns the InstanceName field value if set, zero value otherwise.
func (o *ModifyInstanceNameRequestV2) GetInstanceName() string {
	if o == nil || IsNil(o.InstanceName) {
		var ret string
		return ret
	}
	return *o.InstanceName
}

// GetInstanceNameOk returns a tuple with the InstanceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyInstanceNameRequestV2) GetInstanceNameOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceName) {
		return nil, false
	}
	return o.InstanceName, true
}

// HasInstanceName returns a boolean if a field has been set.
func (o *ModifyInstanceNameRequestV2) HasInstanceName() bool {
	if o != nil && !IsNil(o.InstanceName) {
		return true
	}

	return false
}

// SetInstanceName gets a reference to the given string and assigns it to the InstanceName field.
func (o *ModifyInstanceNameRequestV2) SetInstanceName(v string) {
	o.InstanceName = &v
}

func (o ModifyInstanceNameRequestV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyInstanceNameRequestV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.InstanceName) {
		toSerialize["instanceName"] = o.InstanceName
	}
	return toSerialize, nil
}

type NullableModifyInstanceNameRequestV2 struct {
	value *ModifyInstanceNameRequestV2
	isSet bool
}

func (v NullableModifyInstanceNameRequestV2) Get() *ModifyInstanceNameRequestV2 {
	return v.value
}

func (v *NullableModifyInstanceNameRequestV2) Set(val *ModifyInstanceNameRequestV2) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyInstanceNameRequestV2) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyInstanceNameRequestV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyInstanceNameRequestV2(val *ModifyInstanceNameRequestV2) *NullableModifyInstanceNameRequestV2 {
	return &NullableModifyInstanceNameRequestV2{value: val, isSet: true}
}

func (v NullableModifyInstanceNameRequestV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyInstanceNameRequestV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


