/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the McModifyTenantSecurityIpGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McModifyTenantSecurityIpGroupRequest{}

// McModifyTenantSecurityIpGroupRequest struct for McModifyTenantSecurityIpGroupRequest
type McModifyTenantSecurityIpGroupRequest struct {
	SecurityIps *string `json:"securityIps,omitempty"`
	SecurityIpGroupName *string `json:"securityIpGroupName,omitempty"`
}

// NewMcModifyTenantSecurityIpGroupRequest instantiates a new McModifyTenantSecurityIpGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcModifyTenantSecurityIpGroupRequest() *McModifyTenantSecurityIpGroupRequest {
	this := McModifyTenantSecurityIpGroupRequest{}
	return &this
}

// NewMcModifyTenantSecurityIpGroupRequestWithDefaults instantiates a new McModifyTenantSecurityIpGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcModifyTenantSecurityIpGroupRequestWithDefaults() *McModifyTenantSecurityIpGroupRequest {
	this := McModifyTenantSecurityIpGroupRequest{}
	return &this
}

// GetSecurityIps returns the SecurityIps field value if set, zero value otherwise.
func (o *McModifyTenantSecurityIpGroupRequest) GetSecurityIps() string {
	if o == nil || IsNil(o.SecurityIps) {
		var ret string
		return ret
	}
	return *o.SecurityIps
}

// GetSecurityIpsOk returns a tuple with the SecurityIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McModifyTenantSecurityIpGroupRequest) GetSecurityIpsOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityIps) {
		return nil, false
	}
	return o.SecurityIps, true
}

// HasSecurityIps returns a boolean if a field has been set.
func (o *McModifyTenantSecurityIpGroupRequest) HasSecurityIps() bool {
	if o != nil && !IsNil(o.SecurityIps) {
		return true
	}

	return false
}

// SetSecurityIps gets a reference to the given string and assigns it to the SecurityIps field.
func (o *McModifyTenantSecurityIpGroupRequest) SetSecurityIps(v string) {
	o.SecurityIps = &v
}

// GetSecurityIpGroupName returns the SecurityIpGroupName field value if set, zero value otherwise.
func (o *McModifyTenantSecurityIpGroupRequest) GetSecurityIpGroupName() string {
	if o == nil || IsNil(o.SecurityIpGroupName) {
		var ret string
		return ret
	}
	return *o.SecurityIpGroupName
}

// GetSecurityIpGroupNameOk returns a tuple with the SecurityIpGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McModifyTenantSecurityIpGroupRequest) GetSecurityIpGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityIpGroupName) {
		return nil, false
	}
	return o.SecurityIpGroupName, true
}

// HasSecurityIpGroupName returns a boolean if a field has been set.
func (o *McModifyTenantSecurityIpGroupRequest) HasSecurityIpGroupName() bool {
	if o != nil && !IsNil(o.SecurityIpGroupName) {
		return true
	}

	return false
}

// SetSecurityIpGroupName gets a reference to the given string and assigns it to the SecurityIpGroupName field.
func (o *McModifyTenantSecurityIpGroupRequest) SetSecurityIpGroupName(v string) {
	o.SecurityIpGroupName = &v
}

func (o McModifyTenantSecurityIpGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McModifyTenantSecurityIpGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SecurityIps) {
		toSerialize["securityIps"] = o.SecurityIps
	}
	if !IsNil(o.SecurityIpGroupName) {
		toSerialize["securityIpGroupName"] = o.SecurityIpGroupName
	}
	return toSerialize, nil
}

type NullableMcModifyTenantSecurityIpGroupRequest struct {
	value *McModifyTenantSecurityIpGroupRequest
	isSet bool
}

func (v NullableMcModifyTenantSecurityIpGroupRequest) Get() *McModifyTenantSecurityIpGroupRequest {
	return v.value
}

func (v *NullableMcModifyTenantSecurityIpGroupRequest) Set(val *McModifyTenantSecurityIpGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMcModifyTenantSecurityIpGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMcModifyTenantSecurityIpGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcModifyTenantSecurityIpGroupRequest(val *McModifyTenantSecurityIpGroupRequest) *NullableMcModifyTenantSecurityIpGroupRequest {
	return &NullableMcModifyTenantSecurityIpGroupRequest{value: val, isSet: true}
}

func (v NullableMcModifyTenantSecurityIpGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcModifyTenantSecurityIpGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


