/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ModifyInstanceResponseV2OpenApi type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyInstanceResponseV2OpenApi{}

// ModifyInstanceResponseV2OpenApi struct for ModifyInstanceResponseV2OpenApi
type ModifyInstanceResponseV2OpenApi struct {
	OrderId *string `json:"orderId,omitempty"`
	InstanceId *string `json:"instanceId,omitempty"`
	DryRun *bool `json:"dryRun,omitempty"`
	DryRunResult *bool `json:"dryRunResult,omitempty"`
}

// NewModifyInstanceResponseV2OpenApi instantiates a new ModifyInstanceResponseV2OpenApi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyInstanceResponseV2OpenApi() *ModifyInstanceResponseV2OpenApi {
	this := ModifyInstanceResponseV2OpenApi{}
	return &this
}

// NewModifyInstanceResponseV2OpenApiWithDefaults instantiates a new ModifyInstanceResponseV2OpenApi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyInstanceResponseV2OpenApiWithDefaults() *ModifyInstanceResponseV2OpenApi {
	this := ModifyInstanceResponseV2OpenApi{}
	return &this
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *ModifyInstanceResponseV2OpenApi) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyInstanceResponseV2OpenApi) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *ModifyInstanceResponseV2OpenApi) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *ModifyInstanceResponseV2OpenApi) SetOrderId(v string) {
	o.OrderId = &v
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *ModifyInstanceResponseV2OpenApi) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyInstanceResponseV2OpenApi) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *ModifyInstanceResponseV2OpenApi) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *ModifyInstanceResponseV2OpenApi) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetDryRun returns the DryRun field value if set, zero value otherwise.
func (o *ModifyInstanceResponseV2OpenApi) GetDryRun() bool {
	if o == nil || IsNil(o.DryRun) {
		var ret bool
		return ret
	}
	return *o.DryRun
}

// GetDryRunOk returns a tuple with the DryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyInstanceResponseV2OpenApi) GetDryRunOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRun) {
		return nil, false
	}
	return o.DryRun, true
}

// HasDryRun returns a boolean if a field has been set.
func (o *ModifyInstanceResponseV2OpenApi) HasDryRun() bool {
	if o != nil && !IsNil(o.DryRun) {
		return true
	}

	return false
}

// SetDryRun gets a reference to the given bool and assigns it to the DryRun field.
func (o *ModifyInstanceResponseV2OpenApi) SetDryRun(v bool) {
	o.DryRun = &v
}

// GetDryRunResult returns the DryRunResult field value if set, zero value otherwise.
func (o *ModifyInstanceResponseV2OpenApi) GetDryRunResult() bool {
	if o == nil || IsNil(o.DryRunResult) {
		var ret bool
		return ret
	}
	return *o.DryRunResult
}

// GetDryRunResultOk returns a tuple with the DryRunResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyInstanceResponseV2OpenApi) GetDryRunResultOk() (*bool, bool) {
	if o == nil || IsNil(o.DryRunResult) {
		return nil, false
	}
	return o.DryRunResult, true
}

// HasDryRunResult returns a boolean if a field has been set.
func (o *ModifyInstanceResponseV2OpenApi) HasDryRunResult() bool {
	if o != nil && !IsNil(o.DryRunResult) {
		return true
	}

	return false
}

// SetDryRunResult gets a reference to the given bool and assigns it to the DryRunResult field.
func (o *ModifyInstanceResponseV2OpenApi) SetDryRunResult(v bool) {
	o.DryRunResult = &v
}

func (o ModifyInstanceResponseV2OpenApi) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyInstanceResponseV2OpenApi) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if !IsNil(o.DryRun) {
		toSerialize["dryRun"] = o.DryRun
	}
	if !IsNil(o.DryRunResult) {
		toSerialize["dryRunResult"] = o.DryRunResult
	}
	return toSerialize, nil
}

type NullableModifyInstanceResponseV2OpenApi struct {
	value *ModifyInstanceResponseV2OpenApi
	isSet bool
}

func (v NullableModifyInstanceResponseV2OpenApi) Get() *ModifyInstanceResponseV2OpenApi {
	return v.value
}

func (v *NullableModifyInstanceResponseV2OpenApi) Set(val *ModifyInstanceResponseV2OpenApi) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyInstanceResponseV2OpenApi) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyInstanceResponseV2OpenApi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyInstanceResponseV2OpenApi(val *ModifyInstanceResponseV2OpenApi) *NullableModifyInstanceResponseV2OpenApi {
	return &NullableModifyInstanceResponseV2OpenApi{value: val, isSet: true}
}

func (v NullableModifyInstanceResponseV2OpenApi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyInstanceResponseV2OpenApi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


