/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the CreateTenantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTenantRequest{}

// CreateTenantRequest struct for CreateTenantRequest
type CreateTenantRequest struct {
	InstanceId *string `json:"instanceId,omitempty"`
	TenantName *string `json:"tenantName,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
	TenantMode *string `json:"tenantMode,omitempty"`
	PrimaryZone *string `json:"primaryZone,omitempty"`
	Charset *string `json:"charset,omitempty"`
	Description *string `json:"description,omitempty"`
	Whitelist *string `json:"whitelist,omitempty"`
	TimeZone *string `json:"timeZone,omitempty"`
	Cpu *int32 `json:"cpu,omitempty"`
	Memory *int32 `json:"memory,omitempty"`
	DiskSize *int32 `json:"diskSize,omitempty"`
	UnitNum *int32 `json:"unitNum,omitempty"`
	Environment *string `json:"environment,omitempty"`
	EnablePublicLink *bool `json:"enablePublicLink,omitempty"`
	CreateParams *map[string]string `json:"createParams,omitempty"`
	TenantCompatibilityModeEnum *string `json:"tenantCompatibilityModeEnum,omitempty"`
}

// NewCreateTenantRequest instantiates a new CreateTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTenantRequest() *CreateTenantRequest {
	this := CreateTenantRequest{}
	return &this
}

// NewCreateTenantRequestWithDefaults instantiates a new CreateTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTenantRequestWithDefaults() *CreateTenantRequest {
	this := CreateTenantRequest{}
	return &this
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *CreateTenantRequest) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetTenantName returns the TenantName field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetTenantName() string {
	if o == nil || IsNil(o.TenantName) {
		var ret string
		return ret
	}
	return *o.TenantName
}

// GetTenantNameOk returns a tuple with the TenantName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetTenantNameOk() (*string, bool) {
	if o == nil || IsNil(o.TenantName) {
		return nil, false
	}
	return o.TenantName, true
}

// HasTenantName returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasTenantName() bool {
	if o != nil && !IsNil(o.TenantName) {
		return true
	}

	return false
}

// SetTenantName gets a reference to the given string and assigns it to the TenantName field.
func (o *CreateTenantRequest) SetTenantName(v string) {
	o.TenantName = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *CreateTenantRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetTenantMode returns the TenantMode field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetTenantMode() string {
	if o == nil || IsNil(o.TenantMode) {
		var ret string
		return ret
	}
	return *o.TenantMode
}

// GetTenantModeOk returns a tuple with the TenantMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetTenantModeOk() (*string, bool) {
	if o == nil || IsNil(o.TenantMode) {
		return nil, false
	}
	return o.TenantMode, true
}

// HasTenantMode returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasTenantMode() bool {
	if o != nil && !IsNil(o.TenantMode) {
		return true
	}

	return false
}

// SetTenantMode gets a reference to the given string and assigns it to the TenantMode field.
func (o *CreateTenantRequest) SetTenantMode(v string) {
	o.TenantMode = &v
}

// GetPrimaryZone returns the PrimaryZone field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetPrimaryZone() string {
	if o == nil || IsNil(o.PrimaryZone) {
		var ret string
		return ret
	}
	return *o.PrimaryZone
}

// GetPrimaryZoneOk returns a tuple with the PrimaryZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetPrimaryZoneOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryZone) {
		return nil, false
	}
	return o.PrimaryZone, true
}

// HasPrimaryZone returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasPrimaryZone() bool {
	if o != nil && !IsNil(o.PrimaryZone) {
		return true
	}

	return false
}

// SetPrimaryZone gets a reference to the given string and assigns it to the PrimaryZone field.
func (o *CreateTenantRequest) SetPrimaryZone(v string) {
	o.PrimaryZone = &v
}

// GetCharset returns the Charset field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetCharset() string {
	if o == nil || IsNil(o.Charset) {
		var ret string
		return ret
	}
	return *o.Charset
}

// GetCharsetOk returns a tuple with the Charset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetCharsetOk() (*string, bool) {
	if o == nil || IsNil(o.Charset) {
		return nil, false
	}
	return o.Charset, true
}

// HasCharset returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasCharset() bool {
	if o != nil && !IsNil(o.Charset) {
		return true
	}

	return false
}

// SetCharset gets a reference to the given string and assigns it to the Charset field.
func (o *CreateTenantRequest) SetCharset(v string) {
	o.Charset = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTenantRequest) SetDescription(v string) {
	o.Description = &v
}

// GetWhitelist returns the Whitelist field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetWhitelist() string {
	if o == nil || IsNil(o.Whitelist) {
		var ret string
		return ret
	}
	return *o.Whitelist
}

// GetWhitelistOk returns a tuple with the Whitelist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetWhitelistOk() (*string, bool) {
	if o == nil || IsNil(o.Whitelist) {
		return nil, false
	}
	return o.Whitelist, true
}

// HasWhitelist returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasWhitelist() bool {
	if o != nil && !IsNil(o.Whitelist) {
		return true
	}

	return false
}

// SetWhitelist gets a reference to the given string and assigns it to the Whitelist field.
func (o *CreateTenantRequest) SetWhitelist(v string) {
	o.Whitelist = &v
}

// GetTimeZone returns the TimeZone field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetTimeZone() string {
	if o == nil || IsNil(o.TimeZone) {
		var ret string
		return ret
	}
	return *o.TimeZone
}

// GetTimeZoneOk returns a tuple with the TimeZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetTimeZoneOk() (*string, bool) {
	if o == nil || IsNil(o.TimeZone) {
		return nil, false
	}
	return o.TimeZone, true
}

// HasTimeZone returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasTimeZone() bool {
	if o != nil && !IsNil(o.TimeZone) {
		return true
	}

	return false
}

// SetTimeZone gets a reference to the given string and assigns it to the TimeZone field.
func (o *CreateTenantRequest) SetTimeZone(v string) {
	o.TimeZone = &v
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetCpu() int32 {
	if o == nil || IsNil(o.Cpu) {
		var ret int32
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetCpuOk() (*int32, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given int32 and assigns it to the Cpu field.
func (o *CreateTenantRequest) SetCpu(v int32) {
	o.Cpu = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *CreateTenantRequest) SetMemory(v int32) {
	o.Memory = &v
}

// GetDiskSize returns the DiskSize field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetDiskSize() int32 {
	if o == nil || IsNil(o.DiskSize) {
		var ret int32
		return ret
	}
	return *o.DiskSize
}

// GetDiskSizeOk returns a tuple with the DiskSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetDiskSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.DiskSize) {
		return nil, false
	}
	return o.DiskSize, true
}

// HasDiskSize returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasDiskSize() bool {
	if o != nil && !IsNil(o.DiskSize) {
		return true
	}

	return false
}

// SetDiskSize gets a reference to the given int32 and assigns it to the DiskSize field.
func (o *CreateTenantRequest) SetDiskSize(v int32) {
	o.DiskSize = &v
}

// GetUnitNum returns the UnitNum field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetUnitNum() int32 {
	if o == nil || IsNil(o.UnitNum) {
		var ret int32
		return ret
	}
	return *o.UnitNum
}

// GetUnitNumOk returns a tuple with the UnitNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetUnitNumOk() (*int32, bool) {
	if o == nil || IsNil(o.UnitNum) {
		return nil, false
	}
	return o.UnitNum, true
}

// HasUnitNum returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasUnitNum() bool {
	if o != nil && !IsNil(o.UnitNum) {
		return true
	}

	return false
}

// SetUnitNum gets a reference to the given int32 and assigns it to the UnitNum field.
func (o *CreateTenantRequest) SetUnitNum(v int32) {
	o.UnitNum = &v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetEnvironment() string {
	if o == nil || IsNil(o.Environment) {
		var ret string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetEnvironmentOk() (*string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given string and assigns it to the Environment field.
func (o *CreateTenantRequest) SetEnvironment(v string) {
	o.Environment = &v
}

// GetEnablePublicLink returns the EnablePublicLink field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetEnablePublicLink() bool {
	if o == nil || IsNil(o.EnablePublicLink) {
		var ret bool
		return ret
	}
	return *o.EnablePublicLink
}

// GetEnablePublicLinkOk returns a tuple with the EnablePublicLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetEnablePublicLinkOk() (*bool, bool) {
	if o == nil || IsNil(o.EnablePublicLink) {
		return nil, false
	}
	return o.EnablePublicLink, true
}

// HasEnablePublicLink returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasEnablePublicLink() bool {
	if o != nil && !IsNil(o.EnablePublicLink) {
		return true
	}

	return false
}

// SetEnablePublicLink gets a reference to the given bool and assigns it to the EnablePublicLink field.
func (o *CreateTenantRequest) SetEnablePublicLink(v bool) {
	o.EnablePublicLink = &v
}

// GetCreateParams returns the CreateParams field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetCreateParams() map[string]string {
	if o == nil || IsNil(o.CreateParams) {
		var ret map[string]string
		return ret
	}
	return *o.CreateParams
}

// GetCreateParamsOk returns a tuple with the CreateParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetCreateParamsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.CreateParams) {
		return nil, false
	}
	return o.CreateParams, true
}

// HasCreateParams returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasCreateParams() bool {
	if o != nil && !IsNil(o.CreateParams) {
		return true
	}

	return false
}

// SetCreateParams gets a reference to the given map[string]string and assigns it to the CreateParams field.
func (o *CreateTenantRequest) SetCreateParams(v map[string]string) {
	o.CreateParams = &v
}

// GetTenantCompatibilityModeEnum returns the TenantCompatibilityModeEnum field value if set, zero value otherwise.
func (o *CreateTenantRequest) GetTenantCompatibilityModeEnum() string {
	if o == nil || IsNil(o.TenantCompatibilityModeEnum) {
		var ret string
		return ret
	}
	return *o.TenantCompatibilityModeEnum
}

// GetTenantCompatibilityModeEnumOk returns a tuple with the TenantCompatibilityModeEnum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTenantRequest) GetTenantCompatibilityModeEnumOk() (*string, bool) {
	if o == nil || IsNil(o.TenantCompatibilityModeEnum) {
		return nil, false
	}
	return o.TenantCompatibilityModeEnum, true
}

// HasTenantCompatibilityModeEnum returns a boolean if a field has been set.
func (o *CreateTenantRequest) HasTenantCompatibilityModeEnum() bool {
	if o != nil && !IsNil(o.TenantCompatibilityModeEnum) {
		return true
	}

	return false
}

// SetTenantCompatibilityModeEnum gets a reference to the given string and assigns it to the TenantCompatibilityModeEnum field.
func (o *CreateTenantRequest) SetTenantCompatibilityModeEnum(v string) {
	o.TenantCompatibilityModeEnum = &v
}

func (o CreateTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTenantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if !IsNil(o.TenantName) {
		toSerialize["tenantName"] = o.TenantName
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.TenantMode) {
		toSerialize["tenantMode"] = o.TenantMode
	}
	if !IsNil(o.PrimaryZone) {
		toSerialize["primaryZone"] = o.PrimaryZone
	}
	if !IsNil(o.Charset) {
		toSerialize["charset"] = o.Charset
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Whitelist) {
		toSerialize["whitelist"] = o.Whitelist
	}
	if !IsNil(o.TimeZone) {
		toSerialize["timeZone"] = o.TimeZone
	}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.DiskSize) {
		toSerialize["diskSize"] = o.DiskSize
	}
	if !IsNil(o.UnitNum) {
		toSerialize["unitNum"] = o.UnitNum
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.EnablePublicLink) {
		toSerialize["enablePublicLink"] = o.EnablePublicLink
	}
	if !IsNil(o.CreateParams) {
		toSerialize["createParams"] = o.CreateParams
	}
	if !IsNil(o.TenantCompatibilityModeEnum) {
		toSerialize["tenantCompatibilityModeEnum"] = o.TenantCompatibilityModeEnum
	}
	return toSerialize, nil
}

type NullableCreateTenantRequest struct {
	value *CreateTenantRequest
	isSet bool
}

func (v NullableCreateTenantRequest) Get() *CreateTenantRequest {
	return v.value
}

func (v *NullableCreateTenantRequest) Set(val *CreateTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTenantRequest(val *CreateTenantRequest) *NullableCreateTenantRequest {
	return &NullableCreateTenantRequest{value: val, isSet: true}
}

func (v NullableCreateTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


