/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the McModifyTenantSecurityIpGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &McModifyTenantSecurityIpGroupResponse{}

// McModifyTenantSecurityIpGroupResponse struct for McModifyTenantSecurityIpGroupResponse
type McModifyTenantSecurityIpGroupResponse struct {
	InstanceId *string `json:"instanceId,omitempty"`
	TenantId *string `json:"tenantId,omitempty"`
	SecurityIps *string `json:"securityIps,omitempty"`
	SecurityIpGroupName *string `json:"securityIpGroupName,omitempty"`
}

// NewMcModifyTenantSecurityIpGroupResponse instantiates a new McModifyTenantSecurityIpGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMcModifyTenantSecurityIpGroupResponse() *McModifyTenantSecurityIpGroupResponse {
	this := McModifyTenantSecurityIpGroupResponse{}
	return &this
}

// NewMcModifyTenantSecurityIpGroupResponseWithDefaults instantiates a new McModifyTenantSecurityIpGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMcModifyTenantSecurityIpGroupResponseWithDefaults() *McModifyTenantSecurityIpGroupResponse {
	this := McModifyTenantSecurityIpGroupResponse{}
	return &this
}

// GetInstanceId returns the InstanceId field value if set, zero value otherwise.
func (o *McModifyTenantSecurityIpGroupResponse) GetInstanceId() string {
	if o == nil || IsNil(o.InstanceId) {
		var ret string
		return ret
	}
	return *o.InstanceId
}

// GetInstanceIdOk returns a tuple with the InstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McModifyTenantSecurityIpGroupResponse) GetInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceId) {
		return nil, false
	}
	return o.InstanceId, true
}

// HasInstanceId returns a boolean if a field has been set.
func (o *McModifyTenantSecurityIpGroupResponse) HasInstanceId() bool {
	if o != nil && !IsNil(o.InstanceId) {
		return true
	}

	return false
}

// SetInstanceId gets a reference to the given string and assigns it to the InstanceId field.
func (o *McModifyTenantSecurityIpGroupResponse) SetInstanceId(v string) {
	o.InstanceId = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *McModifyTenantSecurityIpGroupResponse) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McModifyTenantSecurityIpGroupResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *McModifyTenantSecurityIpGroupResponse) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *McModifyTenantSecurityIpGroupResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetSecurityIps returns the SecurityIps field value if set, zero value otherwise.
func (o *McModifyTenantSecurityIpGroupResponse) GetSecurityIps() string {
	if o == nil || IsNil(o.SecurityIps) {
		var ret string
		return ret
	}
	return *o.SecurityIps
}

// GetSecurityIpsOk returns a tuple with the SecurityIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McModifyTenantSecurityIpGroupResponse) GetSecurityIpsOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityIps) {
		return nil, false
	}
	return o.SecurityIps, true
}

// HasSecurityIps returns a boolean if a field has been set.
func (o *McModifyTenantSecurityIpGroupResponse) HasSecurityIps() bool {
	if o != nil && !IsNil(o.SecurityIps) {
		return true
	}

	return false
}

// SetSecurityIps gets a reference to the given string and assigns it to the SecurityIps field.
func (o *McModifyTenantSecurityIpGroupResponse) SetSecurityIps(v string) {
	o.SecurityIps = &v
}

// GetSecurityIpGroupName returns the SecurityIpGroupName field value if set, zero value otherwise.
func (o *McModifyTenantSecurityIpGroupResponse) GetSecurityIpGroupName() string {
	if o == nil || IsNil(o.SecurityIpGroupName) {
		var ret string
		return ret
	}
	return *o.SecurityIpGroupName
}

// GetSecurityIpGroupNameOk returns a tuple with the SecurityIpGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *McModifyTenantSecurityIpGroupResponse) GetSecurityIpGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityIpGroupName) {
		return nil, false
	}
	return o.SecurityIpGroupName, true
}

// HasSecurityIpGroupName returns a boolean if a field has been set.
func (o *McModifyTenantSecurityIpGroupResponse) HasSecurityIpGroupName() bool {
	if o != nil && !IsNil(o.SecurityIpGroupName) {
		return true
	}

	return false
}

// SetSecurityIpGroupName gets a reference to the given string and assigns it to the SecurityIpGroupName field.
func (o *McModifyTenantSecurityIpGroupResponse) SetSecurityIpGroupName(v string) {
	o.SecurityIpGroupName = &v
}

func (o McModifyTenantSecurityIpGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o McModifyTenantSecurityIpGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InstanceId) {
		toSerialize["instanceId"] = o.InstanceId
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.SecurityIps) {
		toSerialize["securityIps"] = o.SecurityIps
	}
	if !IsNil(o.SecurityIpGroupName) {
		toSerialize["securityIpGroupName"] = o.SecurityIpGroupName
	}
	return toSerialize, nil
}

type NullableMcModifyTenantSecurityIpGroupResponse struct {
	value *McModifyTenantSecurityIpGroupResponse
	isSet bool
}

func (v NullableMcModifyTenantSecurityIpGroupResponse) Get() *McModifyTenantSecurityIpGroupResponse {
	return v.value
}

func (v *NullableMcModifyTenantSecurityIpGroupResponse) Set(val *McModifyTenantSecurityIpGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMcModifyTenantSecurityIpGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMcModifyTenantSecurityIpGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMcModifyTenantSecurityIpGroupResponse(val *McModifyTenantSecurityIpGroupResponse) *NullableMcModifyTenantSecurityIpGroupResponse {
	return &NullableMcModifyTenantSecurityIpGroupResponse{value: val, isSet: true}
}

func (v NullableMcModifyTenantSecurityIpGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMcModifyTenantSecurityIpGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


