/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the TenantPrivateLinkDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantPrivateLinkDTO{}

// TenantPrivateLinkDTO struct for TenantPrivateLinkDTO
type TenantPrivateLinkDTO struct {
	PrivateLinkStatus *string `json:"privateLinkStatus,omitempty"`
	PrivateLinkServiceId *string `json:"privateLinkServiceId,omitempty"`
	PrivateLinkEndpointId *string `json:"privateLinkEndpointId,omitempty"`
	PrivateLinkServiceAccount *string `json:"privateLinkServiceAccount,omitempty"`
	PrivateLinkUserAccount *string `json:"privateLinkUserAccount,omitempty"`
	PrivateLinkDomain *string `json:"privateLinkDomain,omitempty"`
	IntranetAddress *string `json:"intranetAddress,omitempty"`
	IntranetDomain *string `json:"intranetDomain,omitempty"`
}

// NewTenantPrivateLinkDTO instantiates a new TenantPrivateLinkDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantPrivateLinkDTO() *TenantPrivateLinkDTO {
	this := TenantPrivateLinkDTO{}
	return &this
}

// NewTenantPrivateLinkDTOWithDefaults instantiates a new TenantPrivateLinkDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantPrivateLinkDTOWithDefaults() *TenantPrivateLinkDTO {
	this := TenantPrivateLinkDTO{}
	return &this
}

// GetPrivateLinkStatus returns the PrivateLinkStatus field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetPrivateLinkStatus() string {
	if o == nil || IsNil(o.PrivateLinkStatus) {
		var ret string
		return ret
	}
	return *o.PrivateLinkStatus
}

// GetPrivateLinkStatusOk returns a tuple with the PrivateLinkStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetPrivateLinkStatusOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateLinkStatus) {
		return nil, false
	}
	return o.PrivateLinkStatus, true
}

// HasPrivateLinkStatus returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasPrivateLinkStatus() bool {
	if o != nil && !IsNil(o.PrivateLinkStatus) {
		return true
	}

	return false
}

// SetPrivateLinkStatus gets a reference to the given string and assigns it to the PrivateLinkStatus field.
func (o *TenantPrivateLinkDTO) SetPrivateLinkStatus(v string) {
	o.PrivateLinkStatus = &v
}

// GetPrivateLinkServiceId returns the PrivateLinkServiceId field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetPrivateLinkServiceId() string {
	if o == nil || IsNil(o.PrivateLinkServiceId) {
		var ret string
		return ret
	}
	return *o.PrivateLinkServiceId
}

// GetPrivateLinkServiceIdOk returns a tuple with the PrivateLinkServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetPrivateLinkServiceIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateLinkServiceId) {
		return nil, false
	}
	return o.PrivateLinkServiceId, true
}

// HasPrivateLinkServiceId returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasPrivateLinkServiceId() bool {
	if o != nil && !IsNil(o.PrivateLinkServiceId) {
		return true
	}

	return false
}

// SetPrivateLinkServiceId gets a reference to the given string and assigns it to the PrivateLinkServiceId field.
func (o *TenantPrivateLinkDTO) SetPrivateLinkServiceId(v string) {
	o.PrivateLinkServiceId = &v
}

// GetPrivateLinkEndpointId returns the PrivateLinkEndpointId field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetPrivateLinkEndpointId() string {
	if o == nil || IsNil(o.PrivateLinkEndpointId) {
		var ret string
		return ret
	}
	return *o.PrivateLinkEndpointId
}

// GetPrivateLinkEndpointIdOk returns a tuple with the PrivateLinkEndpointId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetPrivateLinkEndpointIdOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateLinkEndpointId) {
		return nil, false
	}
	return o.PrivateLinkEndpointId, true
}

// HasPrivateLinkEndpointId returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasPrivateLinkEndpointId() bool {
	if o != nil && !IsNil(o.PrivateLinkEndpointId) {
		return true
	}

	return false
}

// SetPrivateLinkEndpointId gets a reference to the given string and assigns it to the PrivateLinkEndpointId field.
func (o *TenantPrivateLinkDTO) SetPrivateLinkEndpointId(v string) {
	o.PrivateLinkEndpointId = &v
}

// GetPrivateLinkServiceAccount returns the PrivateLinkServiceAccount field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetPrivateLinkServiceAccount() string {
	if o == nil || IsNil(o.PrivateLinkServiceAccount) {
		var ret string
		return ret
	}
	return *o.PrivateLinkServiceAccount
}

// GetPrivateLinkServiceAccountOk returns a tuple with the PrivateLinkServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetPrivateLinkServiceAccountOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateLinkServiceAccount) {
		return nil, false
	}
	return o.PrivateLinkServiceAccount, true
}

// HasPrivateLinkServiceAccount returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasPrivateLinkServiceAccount() bool {
	if o != nil && !IsNil(o.PrivateLinkServiceAccount) {
		return true
	}

	return false
}

// SetPrivateLinkServiceAccount gets a reference to the given string and assigns it to the PrivateLinkServiceAccount field.
func (o *TenantPrivateLinkDTO) SetPrivateLinkServiceAccount(v string) {
	o.PrivateLinkServiceAccount = &v
}

// GetPrivateLinkUserAccount returns the PrivateLinkUserAccount field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetPrivateLinkUserAccount() string {
	if o == nil || IsNil(o.PrivateLinkUserAccount) {
		var ret string
		return ret
	}
	return *o.PrivateLinkUserAccount
}

// GetPrivateLinkUserAccountOk returns a tuple with the PrivateLinkUserAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetPrivateLinkUserAccountOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateLinkUserAccount) {
		return nil, false
	}
	return o.PrivateLinkUserAccount, true
}

// HasPrivateLinkUserAccount returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasPrivateLinkUserAccount() bool {
	if o != nil && !IsNil(o.PrivateLinkUserAccount) {
		return true
	}

	return false
}

// SetPrivateLinkUserAccount gets a reference to the given string and assigns it to the PrivateLinkUserAccount field.
func (o *TenantPrivateLinkDTO) SetPrivateLinkUserAccount(v string) {
	o.PrivateLinkUserAccount = &v
}

// GetPrivateLinkDomain returns the PrivateLinkDomain field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetPrivateLinkDomain() string {
	if o == nil || IsNil(o.PrivateLinkDomain) {
		var ret string
		return ret
	}
	return *o.PrivateLinkDomain
}

// GetPrivateLinkDomainOk returns a tuple with the PrivateLinkDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetPrivateLinkDomainOk() (*string, bool) {
	if o == nil || IsNil(o.PrivateLinkDomain) {
		return nil, false
	}
	return o.PrivateLinkDomain, true
}

// HasPrivateLinkDomain returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasPrivateLinkDomain() bool {
	if o != nil && !IsNil(o.PrivateLinkDomain) {
		return true
	}

	return false
}

// SetPrivateLinkDomain gets a reference to the given string and assigns it to the PrivateLinkDomain field.
func (o *TenantPrivateLinkDTO) SetPrivateLinkDomain(v string) {
	o.PrivateLinkDomain = &v
}

// GetIntranetAddress returns the IntranetAddress field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetIntranetAddress() string {
	if o == nil || IsNil(o.IntranetAddress) {
		var ret string
		return ret
	}
	return *o.IntranetAddress
}

// GetIntranetAddressOk returns a tuple with the IntranetAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetIntranetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.IntranetAddress) {
		return nil, false
	}
	return o.IntranetAddress, true
}

// HasIntranetAddress returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasIntranetAddress() bool {
	if o != nil && !IsNil(o.IntranetAddress) {
		return true
	}

	return false
}

// SetIntranetAddress gets a reference to the given string and assigns it to the IntranetAddress field.
func (o *TenantPrivateLinkDTO) SetIntranetAddress(v string) {
	o.IntranetAddress = &v
}

// GetIntranetDomain returns the IntranetDomain field value if set, zero value otherwise.
func (o *TenantPrivateLinkDTO) GetIntranetDomain() string {
	if o == nil || IsNil(o.IntranetDomain) {
		var ret string
		return ret
	}
	return *o.IntranetDomain
}

// GetIntranetDomainOk returns a tuple with the IntranetDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantPrivateLinkDTO) GetIntranetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.IntranetDomain) {
		return nil, false
	}
	return o.IntranetDomain, true
}

// HasIntranetDomain returns a boolean if a field has been set.
func (o *TenantPrivateLinkDTO) HasIntranetDomain() bool {
	if o != nil && !IsNil(o.IntranetDomain) {
		return true
	}

	return false
}

// SetIntranetDomain gets a reference to the given string and assigns it to the IntranetDomain field.
func (o *TenantPrivateLinkDTO) SetIntranetDomain(v string) {
	o.IntranetDomain = &v
}

func (o TenantPrivateLinkDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantPrivateLinkDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrivateLinkStatus) {
		toSerialize["privateLinkStatus"] = o.PrivateLinkStatus
	}
	if !IsNil(o.PrivateLinkServiceId) {
		toSerialize["privateLinkServiceId"] = o.PrivateLinkServiceId
	}
	if !IsNil(o.PrivateLinkEndpointId) {
		toSerialize["privateLinkEndpointId"] = o.PrivateLinkEndpointId
	}
	if !IsNil(o.PrivateLinkServiceAccount) {
		toSerialize["privateLinkServiceAccount"] = o.PrivateLinkServiceAccount
	}
	if !IsNil(o.PrivateLinkUserAccount) {
		toSerialize["privateLinkUserAccount"] = o.PrivateLinkUserAccount
	}
	if !IsNil(o.PrivateLinkDomain) {
		toSerialize["privateLinkDomain"] = o.PrivateLinkDomain
	}
	if !IsNil(o.IntranetAddress) {
		toSerialize["intranetAddress"] = o.IntranetAddress
	}
	if !IsNil(o.IntranetDomain) {
		toSerialize["intranetDomain"] = o.IntranetDomain
	}
	return toSerialize, nil
}

type NullableTenantPrivateLinkDTO struct {
	value *TenantPrivateLinkDTO
	isSet bool
}

func (v NullableTenantPrivateLinkDTO) Get() *TenantPrivateLinkDTO {
	return v.value
}

func (v *NullableTenantPrivateLinkDTO) Set(val *TenantPrivateLinkDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantPrivateLinkDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantPrivateLinkDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantPrivateLinkDTO(val *TenantPrivateLinkDTO) *NullableTenantPrivateLinkDTO {
	return &NullableTenantPrivateLinkDTO{value: val, isSet: true}
}

func (v NullableTenantPrivateLinkDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantPrivateLinkDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


