/*
OceanBase Cloud API

API Documentation for OceanBase Cloud

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package obcloudsdk

import (
	"encoding/json"
)

// checks if the ModifyDatabaseDescriptionResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyDatabaseDescriptionResponseV2{}

// ModifyDatabaseDescriptionResponseV2 struct for ModifyDatabaseDescriptionResponseV2
type ModifyDatabaseDescriptionResponseV2 struct {
	RequestId *string `json:"requestId,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewModifyDatabaseDescriptionResponseV2 instantiates a new ModifyDatabaseDescriptionResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyDatabaseDescriptionResponseV2() *ModifyDatabaseDescriptionResponseV2 {
	this := ModifyDatabaseDescriptionResponseV2{}
	return &this
}

// NewModifyDatabaseDescriptionResponseV2WithDefaults instantiates a new ModifyDatabaseDescriptionResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyDatabaseDescriptionResponseV2WithDefaults() *ModifyDatabaseDescriptionResponseV2 {
	this := ModifyDatabaseDescriptionResponseV2{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ModifyDatabaseDescriptionResponseV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyDatabaseDescriptionResponseV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ModifyDatabaseDescriptionResponseV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ModifyDatabaseDescriptionResponseV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModifyDatabaseDescriptionResponseV2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyDatabaseDescriptionResponseV2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModifyDatabaseDescriptionResponseV2) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModifyDatabaseDescriptionResponseV2) SetDescription(v string) {
	o.Description = &v
}

func (o ModifyDatabaseDescriptionResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyDatabaseDescriptionResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableModifyDatabaseDescriptionResponseV2 struct {
	value *ModifyDatabaseDescriptionResponseV2
	isSet bool
}

func (v NullableModifyDatabaseDescriptionResponseV2) Get() *ModifyDatabaseDescriptionResponseV2 {
	return v.value
}

func (v *NullableModifyDatabaseDescriptionResponseV2) Set(val *ModifyDatabaseDescriptionResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyDatabaseDescriptionResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyDatabaseDescriptionResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyDatabaseDescriptionResponseV2(val *ModifyDatabaseDescriptionResponseV2) *NullableModifyDatabaseDescriptionResponseV2 {
	return &NullableModifyDatabaseDescriptionResponseV2{value: val, isSet: true}
}

func (v NullableModifyDatabaseDescriptionResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyDatabaseDescriptionResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


